// <auto-generated />
using System;
using Inventario.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Inventario.Infrastructure.Data.Migrations
{
    [DbContext(typeof(InventarioContext))]
    [Migration("20210503235912_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Inventario.Domain.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Costo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductoCompuestoId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductoCompuestoId1");

                    b.ToTable("Productos");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Producto");
                });

            modelBuilder.Entity("Inventario.Domain.ProductoCompuesto", b =>
                {
                    b.HasBaseType("Inventario.Domain.Producto");

                    b.HasDiscriminator().HasValue("ProductoCompuesto");
                });

            modelBuilder.Entity("Inventario.Domain.ProductoSimple", b =>
                {
                    b.HasBaseType("Inventario.Domain.Producto");

                    b.HasDiscriminator().HasValue("ProductoSimple");
                });

            modelBuilder.Entity("Inventario.Domain.Producto", b =>
                {
                    b.HasOne("Inventario.Domain.ProductoCompuesto", null)
                        .WithMany("Ingredientes")
                        .HasForeignKey("ProductoCompuestoId1");
                });

            modelBuilder.Entity("Inventario.Domain.ProductoCompuesto", b =>
                {
                    b.Navigation("Ingredientes");
                });
#pragma warning restore 612, 618
        }
    }
}
